apiVersion: v1
kind: Secret
metadata:
    name: secret
type: Opaque
data:
    github-username: TmF5YW5hLU5hZ2FyYWo=
    github-password: Z2hwX3FVQURqejZrQWk4YWM4cXRLaUw1UjFPTjh4eUQ2RDNPSGtBcw==